name: 'Dev-Branch-CI'

on:
  push:
    branches: [ "EXP-*" ]

permissions:
  contents: read

jobs:
  DevBranchCI:
    name: 'DevBranchCI'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS Dependencies
        run: npm install

      - name: Run Test Cases
        run: echo npm test
