name: 'Main-Branch-CI'

on:
  push:
    branches: [ "main" ]

jobs:
  MainBranchCI:
    name: 'MainBranchCI'
    runs-on: self-hosted
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install NodeJS Dependencies
        run: npm install